layout_spectrum: 1
color:
  saturation: 0.3655914
  brandStrength: 0.5215054
  lightness: 0.5088282
  brandColors:
    - '#151517'
    - '#BDBCBE'
    - '#DFDFE1'
    - '#5B5B5D'
  rhythmicContrast: 0.7936538
typography_spectrum: 0.6702509
name: Michael Ryan Yoga
